function generateDocument() {

    let type = document.getElementById("documentType").value;
    let name = document.getElementById("name").value;
    let address = document.getElementById("address").value;
    let details = document.getElementById("details").value;

    if (name === "" || address === "" || details === "") {
        alert("Please fill all the details.");
        return;
    }

    let documentText =
        "LEGAL DOCUMENT\n\n" +
        "Document Type: " + type + "\n\n" +
        "Name: " + name + "\n" +
        "Address: " + address + "\n\n" +
        "Details:\n" + details + "\n\n" +
        "Generated by LegalEase.";

    document.getElementById("result").style.display = "block";
    document.getElementById("result").innerText = documentText;
}
